// Compatibility shim for Flutter Gradle plugin on Gradle 8+
try {
    org.gradle.api.tasks.bundling.Jar.metaClass.destinationDir = { Object dir ->
        delegate.destinationDirectory.set(project.file(dir))
    }
    org.gradle.api.tasks.bundling.Jar.metaClass.archiveName = { String name ->
        delegate.archiveFileName.set(name)
    }
} catch (Throwable e) {}

buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
